# Generated by Django 4.0 on 2021-12-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('meeting', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('meeting', 'name')},
            },
        ),
    ]
