# Generated by Django 4.0 on 2021-12-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0003_meetingpreference_acceptable_meeting_methods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpreference',
            name='preferred_attending_frequency_in_months',
            field=models.IntegerField(null=True),
        ),
    ]
