# Generated by Django 4.0 on 2021-12-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reunion', '0004_alter_meetingpreference_preferred_attending_frequency_in_months'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
